let number1=4;
let number2=3;
let sum=number1+number2;
let mul=number1*number2;
let sub=number1-number2;
let div=number1/number2;
let power=number1^number2;
console.log("hema");
console.log("2");
console.log("3");
console.log("4");
console.log(`ipower:${power}`);
console.log(`usum:${sum}`);
console.log(`mmul:${mul}`);
console.log(`msub:${sub}`);
console.log(`fdiv:${div}`);